import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '../../components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat gpt clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
        
        <div className="flex">
          <div className='bg-white max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
        {/* Sidebar */}
            <SideBar />
          </div>


        {/*ClientProvider*/}
        <div className='flex-1'>{children}</div>

        </div>
        
        
        </body>
    </html>
  )
}
